service: grafico-linea-8

provider:
  name: aws
  runtime: nodejs14.x
  stage: lin
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'